name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  build:
    name: Builds docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download deps
        run: yarn

      - name: Build docs
        working-directory: ./docs
        run: yarn build

      - name: Upload docs as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .docs/out/


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
